FROM nvidia/cuda:12.9.0-devel-ubuntu24.04

# Set non-interactive mode to avoid apt-get prompts
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    cgdb \
    wget \
    gfortran \
    git \
    scons \
    python3 \
    libfftw3-dev \
    libblas-dev \
    liblapack-dev \
    libgsl-dev \
    openmpi-bin \
    libopenmpi-dev \
    vim \
    nodejs \
    npm \
    clangd \
    && rm -rf /var/lib/apt/lists/*

RUN wget https://github.com/Kitware/CMake/releases/download/v4.1.2/cmake-4.1.2-linux-x86_64.tar.gz \
    && tar -zxvf cmake-4.1.2-linux-x86_64.tar.gz -C /opt/ \
    && ln -s /opt/cmake-4.1.2-linux-x86_64/bin/* /usr/local/bin/ \
    && rm cmake-4.1.2-linux-x86_64.tar.gz

WORKDIR /opt

# Create a build directory inside the container
WORKDIR /opt/build
